Traceback (most recent call last):
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\yla\AppData\Local\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\yla\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import time
import win32com.client  
import pythoncom
import pylab as pl
import numpy as np
import matplotlib.pyplot as plt

from sys import exit
from scipy import signal
from nifpga import Session
from IPython import display
from joblib import Parallel, delayed
from skimage.registration import phase_cross_correlation
from scipy.ndimage import fourier_shift

import warnings
warnings.filterwarnings('ignore')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 11[0m
[0;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01msys[39;00m [38;5;28;01mimport[39;00m exit
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m signal
[1;32m---> 11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnifpga[39;00m [38;5;28;01mimport[39;00m Session
[0;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m [38;5;28;01mimport[39;00m display
[0;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjoblib[39;00m [38;5;28;01mimport[39;00m Parallel, delayed

[1;31mModuleNotFoundError[0m: No module named 'nifpga'
ModuleNotFoundError: No module named 'nifpga'

